language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $gh_token
  keep_history: true
  target-branch: gh-pages
  on:
    branch: master
