language: node_js
node_js:
  - lts/*
before_install:
  - export TZ='Asia/Shanghai'
install:
  - npm install
script:
  - npm run build
  - echo "icyfenix.cn" >> .vuepress/dist/CNAME
after_script:
  # 编译PDF，耗时较长，平时可以注释掉
  - echo "Start PDF Export"
  - sudo apt-get update
  - sudo apt-get -y install xfonts-utils fonts-droid-fallback xfonts-intl-asian
  - sudo cp .vuepress/font/*.* /usr/share/fonts/truetype/
  - sudo mkfontscale && mkfontdir && fc-cache
  - npm run export
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: .vuepress/dist
    github_token: $gh_token
    keep_history: true
    target-branch: gh-pages
    on:
      branch: master
  - provider: script
    keep_history: true
    skip_cleanup: true
    script: npm run deoply:refresh-cdn
    on:
      branch: master
