language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: 8e176ef91989e458ae691f60c469d0a491de9330
  keep_history: true
  target-branch: gh-pages
  on:
    branch: master
