name: Generate Github-Pages from markdown files

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /home/runner/work/awesome-fenix/awesome-fenix
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2

      - name: Run Export
        run: |
          export TZ='Asia/Shanghai'
          npm install
          echo "icyfenix.cn" >> .vuepress/dist/CNAME
          echo "Starting to Export PDF..."
          sudo apt-get update
          sudo apt-get -y install xfonts-utils fonts-droid-fallback xfonts-intl-asian
          sudo cp .vuepress/font/*.* /usr/share/fonts/truetype/
          sudo mkfontscale && mkfontdir && fc-cache
          npm run export

      - name: Deploy Github-Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: vuepress/dist

      - name: Refresh CDN
        run: npm run deoply:refresh-cdn
