name: Generate PDF

on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/checkout@v2

      - name: Install Rclone
        run: curl https://rclone.org/install.sh | sudo bash

      - name: Rclone conf
        run: |
          mkdir -p ~/.config/rclone/
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONF }}
          EOF

      - name: Run Export
        run: |
          export TZ='Asia/Shanghai'
          npm install
          npm run export
      - name: Upload File
        run: rclone copy ./*.pdf jg:notes
